In [1]:
!pip install nltk

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from collections import Counter
from torch.utils.data import Dataset, DataLoader
from nltk.tokenize import word_tokenize
import nltk

In [3]:
document= """The Last Train Journey

On a cold winter evening, Daniel arrived at the old railway station carrying a small leather bag.
The station was nearly empty except for a few passengers waiting quietly on wooden benches.
A loud whistle echoed through the air as the final train of the night slowly entered the platform.

Daniel checked the ticket in his pocket and walked toward the train.
The metal doors opened with a creaking sound and warm air rushed outside.
Inside the train, yellow lights flickered softly above rows of empty seats.

He chose a seat beside the window and placed his bag carefully near his feet.
As the train began to move, the city lights slowly disappeared behind thick clouds of fog.
Snow started falling gently outside while distant mountains appeared under the moonlight.

Across the aisle sat an elderly woman reading an old book with a blue cover.
Every few minutes she looked outside the window as if searching for something familiar.
Daniel noticed a silver necklace around her neck shaped like a small compass.

After several hours, the train stopped at a remote station surrounded by tall pine trees.
Very few people entered or left the train at that place.
A strange silence covered the station as the doors closed once again.

Curious about the woman, Daniel finally started a conversation.
The woman introduced herself as Eleanor and explained that she was returning to her hometown after many years.
She said the town was hidden deep within the northern mountains and was known for its beautiful frozen lake.

As the journey continued, Eleanor shared stories from her childhood.
She described colorful festivals, music performances, and lanterns floating across the lake during winter nights.
Daniel listened carefully while the train moved through snowy valleys and dark forests.

Near midnight, the train suddenly slowed down because heavy snow had covered the tracks ahead.
Passengers became nervous and began discussing possible delays.
Conductors moved through the cabins trying to calm everyone.

Daniel looked outside and saw workers removing snow under bright floodlights.
The freezing wind shook the train slightly while snow continued falling from the dark sky.
Despite the delay, Eleanor remained calm and continued telling her stories.

Several hours later, the tracks were finally cleared and the train resumed its journey.
The passengers sighed with relief as warm coffee was served throughout the cabins.
Daniel and Eleanor continued talking about travel, history, and forgotten places around the world.

Just before sunrise, the train reached the mountain town.
The station was small but beautifully decorated with glowing lamps and snow-covered rooftops.
People wearing thick winter coats walked slowly across the icy streets.

Before leaving, Eleanor handed Daniel a folded piece of paper.
Inside it was a drawing of the frozen lake along with a short message thanking him for the conversation.
Daniel smiled and carefully placed the paper inside his notebook.

As the train departed once again, Daniel stood on the platform watching the sunrise over the mountains.
The cold air, quiet streets, and distant church bells created a peaceful atmosphere he would never forget.
Years later, Daniel would still remember that mysterious winter journey and the stories shared by Eleanor on the last train of the night.
"""

In [4]:
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [5]:
tokens = word_tokenize(document)
tokens

['The',
 'Last',
 'Train',
 'Journey',
 'On',
 'a',
 'cold',
 'winter',
 'evening',
 ',',
 'Daniel',
 'arrived',
 'at',
 'the',
 'old',
 'railway',
 'station',
 'carrying',
 'a',
 'small',
 'leather',
 'bag',
 '.',
 'The',
 'station',
 'was',
 'nearly',
 'empty',
 'except',
 'for',
 'a',
 'few',
 'passengers',
 'waiting',
 'quietly',
 'on',
 'wooden',
 'benches',
 '.',
 'A',
 'loud',
 'whistle',
 'echoed',
 'through',
 'the',
 'air',
 'as',
 'the',
 'final',
 'train',
 'of',
 'the',
 'night',
 'slowly',
 'entered',
 'the',
 'platform',
 '.',
 'Daniel',
 'checked',
 'the',
 'ticket',
 'in',
 'his',
 'pocket',
 'and',
 'walked',
 'toward',
 'the',
 'train',
 '.',
 'The',
 'metal',
 'doors',
 'opened',
 'with',
 'a',
 'creaking',
 'sound',
 'and',
 'warm',
 'air',
 'rushed',
 'outside',
 '.',
 'Inside',
 'the',
 'train',
 ',',
 'yellow',
 'lights',
 'flickered',
 'softly',
 'above',
 'rows',
 'of',
 'empty',
 'seats',
 '.',
 'He',
 'chose',
 'a',
 'seat',
 'beside',
 'the',
 'window',
 'a

Build Vocabs

In [6]:
vocab= {'<unk>':0}

In [7]:
for token in Counter(tokens).keys():
  if token not in vocab:
    vocab[token]=len(vocab)

vocab                       #unique keysfor token

{'<unk>': 0,
 'The': 1,
 'Last': 2,
 'Train': 3,
 'Journey': 4,
 'On': 5,
 'a': 6,
 'cold': 7,
 'winter': 8,
 'evening': 9,
 ',': 10,
 'Daniel': 11,
 'arrived': 12,
 'at': 13,
 'the': 14,
 'old': 15,
 'railway': 16,
 'station': 17,
 'carrying': 18,
 'small': 19,
 'leather': 20,
 'bag': 21,
 '.': 22,
 'was': 23,
 'nearly': 24,
 'empty': 25,
 'except': 26,
 'for': 27,
 'few': 28,
 'passengers': 29,
 'waiting': 30,
 'quietly': 31,
 'on': 32,
 'wooden': 33,
 'benches': 34,
 'A': 35,
 'loud': 36,
 'whistle': 37,
 'echoed': 38,
 'through': 39,
 'air': 40,
 'as': 41,
 'final': 42,
 'train': 43,
 'of': 44,
 'night': 45,
 'slowly': 46,
 'entered': 47,
 'platform': 48,
 'checked': 49,
 'ticket': 50,
 'in': 51,
 'his': 52,
 'pocket': 53,
 'and': 54,
 'walked': 55,
 'toward': 56,
 'metal': 57,
 'doors': 58,
 'opened': 59,
 'with': 60,
 'creaking': 61,
 'sound': 62,
 'warm': 63,
 'rushed': 64,
 'outside': 65,
 'Inside': 66,
 'yellow': 67,
 'lights': 68,
 'flickered': 69,
 'softly': 70,
 'above': 71

In [8]:
len(vocab)

303

extract sentences from data

In [9]:
input_sentences = document.split('\n')
input_sentences[3]

'The station was nearly empty except for a few passengers waiting quietly on wooden benches.'

In [10]:
def text_to_indices(sentence,vocab):
  numerical_sentence = []
  for token in sentence:
    if token in vocab:
      numerical_sentence.append(vocab[token])
    else:
      numerical_sentence.append(vocab['<unk>'])

  return numerical_sentence

In [11]:
input_numerical_sentence= []
for sentence in input_sentences:
  input_numerical_sentence.append(text_to_indices(word_tokenize(sentence.lower()),vocab))


In [12]:
input_numerical_sentence

[[14, 302, 43, 177],
 [],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17, 18, 6, 19, 20, 21, 22],
 [14, 17, 23, 24, 25, 26, 27, 6, 28, 29, 30, 31, 32, 33, 34, 22],
 [6, 36, 37, 38, 39, 14, 40, 41, 14, 42, 43, 44, 14, 45, 46, 47, 14, 48, 22],
 [],
 [0, 49, 14, 50, 51, 52, 53, 54, 55, 56, 14, 43, 22],
 [14, 57, 58, 59, 60, 6, 61, 62, 54, 63, 40, 64, 65, 22],
 [282, 14, 43, 10, 67, 68, 69, 70, 71, 72, 44, 25, 73, 22],
 [],
 [294, 75, 6, 76, 77, 14, 78, 54, 79, 52, 21, 80, 81, 52, 82, 22],
 [41, 14, 43, 84, 85, 86, 10, 14, 87, 68, 46, 88, 89, 90, 91, 44, 92, 22],
 [206, 94, 95, 96, 65, 97, 98, 99, 100, 101, 14, 102, 22],
 [],
 [190, 14, 104, 105, 106, 107, 108, 109, 106, 15, 110, 60, 6, 111, 112, 22],
 [0, 28, 114, 115, 116, 65, 14, 78, 41, 117, 118, 27, 119, 120, 22],
 [0, 121, 6, 122, 123, 124, 125, 126, 127, 128, 6, 19, 129, 22],
 [],
 [162, 131, 132, 10, 14, 43, 133, 13, 6, 134, 17, 135, 136, 137, 138, 139, 22],
 [0, 28, 141, 47, 142, 143, 14, 43, 13, 144, 145, 22],
 [6, 146, 147, 148

training sequence form

In [13]:
training_sequence = []
for sentence in input_numerical_sentence:
  for i in range(1,len(sentence)):
    training_sequence.append(sentence[:i+1])

In [14]:
training_sequence

[[14, 302],
 [14, 302, 43],
 [14, 302, 43, 177],
 [32, 6],
 [32, 6, 7],
 [32, 6, 7, 8],
 [32, 6, 7, 8, 9],
 [32, 6, 7, 8, 9, 10],
 [32, 6, 7, 8, 9, 10, 0],
 [32, 6, 7, 8, 9, 10, 0, 12],
 [32, 6, 7, 8, 9, 10, 0, 12, 13],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17, 18],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17, 18, 6],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17, 18, 6, 19],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17, 18, 6, 19, 20],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17, 18, 6, 19, 20, 21],
 [32, 6, 7, 8, 9, 10, 0, 12, 13, 14, 15, 16, 17, 18, 6, 19, 20, 21, 22],
 [14, 17],
 [14, 17, 23],
 [14, 17, 23, 24],
 [14, 17, 23, 24, 25],
 [14, 17, 23, 24, 25, 26],
 [14, 17, 23, 24, 25, 26, 27],
 [14, 17, 23, 24, 25, 26, 27, 6],
 [14, 17, 23, 24, 25, 26, 27, 6, 28],
 [14, 17, 23, 24, 25, 26, 2

In [15]:
len(training_sequence)

555

In [16]:
training_sequence[:5]

[[14, 302], [14, 302, 43], [14, 302, 43, 177], [32, 6], [32, 6, 7]]

In [17]:
len_list =[]
for sequence in training_sequence:
  len_list.append(len(sequence))

In [18]:
max(len_list)

25

In [19]:
padded_training_sequence =[]
for sequence in training_sequence:
  padded_training_sequence.append([0]*(max(len_list)-len(sequence))+sequence)

In [20]:
padded_training_sequence[3]

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 32, 6]

tensor convert

In [21]:
padded_training_sequence = torch.tensor(padded_training_sequence, dtype=torch.long)

In [22]:
padded_training_sequence

tensor([[  0,   0,   0,  ...,   0,  14, 302],
        [  0,   0,   0,  ...,  14, 302,  43],
        [  0,   0,   0,  ..., 302,  43, 177],
        ...,
        [  0,   0, 164,  ...,  43,  44,  14],
        [  0, 164, 236,  ...,  44,  14,  45],
        [164, 236,  10,  ...,  14,  45,  22]])

In [23]:
X= padded_training_sequence[:,:-1]
X

tensor([[  0,   0,   0,  ...,   0,   0,  14],
        [  0,   0,   0,  ...,   0,  14, 302],
        [  0,   0,   0,  ...,  14, 302,  43],
        ...,
        [  0,   0, 164,  ..., 302,  43,  44],
        [  0, 164, 236,  ...,  43,  44,  14],
        [164, 236,  10,  ...,  44,  14,  45]])

In [24]:
y= padded_training_sequence[:,-1]
y

tensor([302,  43, 177,   6,   7,   8,   9,  10,   0,  12,  13,  14,  15,  16,
         17,  18,   6,  19,  20,  21,  22,  17,  23,  24,  25,  26,  27,   6,
         28,  29,  30,  31,  32,  33,  34,  22,  36,  37,  38,  39,  14,  40,
         41,  14,  42,  43,  44,  14,  45,  46,  47,  14,  48,  22,  49,  14,
         50,  51,  52,  53,  54,  55,  56,  14,  43,  22,  57,  58,  59,  60,
          6,  61,  62,  54,  63,  40,  64,  65,  22,  14,  43,  10,  67,  68,
         69,  70,  71,  72,  44,  25,  73,  22,  75,   6,  76,  77,  14,  78,
         54,  79,  52,  21,  80,  81,  52,  82,  22,  14,  43,  84,  85,  86,
         10,  14,  87,  68,  46,  88,  89,  90,  91,  44,  92,  22,  94,  95,
         96,  65,  97,  98,  99, 100, 101,  14, 102,  22,  14, 104, 105, 106,
        107, 108, 109, 106,  15, 110,  60,   6, 111, 112,  22,  28, 114, 115,
        116,  65,  14,  78,  41, 117, 118,  27, 119, 120,  22, 121,   6, 122,
        123, 124, 125, 126, 127, 128,   6,  19, 129,  22, 131, 1

Custom Dataset and DataLoader

In [25]:
class CustomDataset(Dataset):
  def __init__(self,X,y):
    self.X=X
    self.y=y
  def __len__(self):
    return self.X.shape[0]
  def __getitem__(self, index):
    return self.X[index], self.y[index]

In [26]:
dataset = CustomDataset(X,y)

In [27]:
len(dataset)

555

In [28]:
dataloader = DataLoader(dataset, batch_size=32,shuffle=True)

In [32]:
for input, output in dataloader:
  print(input,output)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,  14,  17,  23,  24,  25,  26,  27,   6],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,  28, 141,  47, 142, 143],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   6, 146],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         131, 132, 236,  10,  14, 208, 237, 154, 238,  54],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0, 252, 269,  10,   0, 270,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,  41,  14,  43,  84,  85],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,  14, 232,  10,   0, 233, 219,  54, 178],
        [  0,   0,   0,   0

In [33]:
X.shape

torch.Size([555, 24])

In [34]:
X[0]

tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0,  0,  0, 14])

In [36]:
X[554]

tensor([164, 236,  10,   0, 295, 299, 300, 144, 301,   8, 177,  54,  14, 180,
        179, 136,   0,  32,  14, 302,  43,  44,  14,  45])

LSTM cell

In [37]:
class LSTMModel(nn.Module):
  def __init__(self,vocab_size):
    super().__init__()
    self.embedding = nn.Embedding(vocab_size,100)
    self.lstm = nn.LSTM(100,150,batch_first=True)
    self.fc = nn.Linear(150, vocab_size)

  def forward(self, x):
    embedded = self.embedding(x)
    intermediate_hidden_states,(final_hidden_states,final_cell_state)= self.lstm(embedded)
    output = self.fc(final_hidden_states.squeeze(0))
    return output

In [38]:
model = LSTMModel(len(vocab))

In [39]:
device = torch.device("cuda"if torch.cuda.is_available() else "cpu")

In [40]:
model.to(device)

LSTMModel(
  (embedding): Embedding(303, 100)
  (lstm): LSTM(100, 150, batch_first=True)
  (fc): Linear(in_features=150, out_features=303, bias=True)
)

Training Loop

In [41]:
epochs = 50
learning_rate = 0.001
criterion = nn.CrossEntropyLoss()

In [42]:
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [44]:
for epoch in range (epochs):
  total_loss =0

  for batch_x , batch_y in dataloader:
    batch_x , batch_y = batch_x.to(device),batch_y.to(device)
    optimizer.zero_grad()

    output = model(batch_x)

    loss = criterion(output, batch_y)

    loss.backward()

    optimizer.step()

    total_loss = total_loss + loss.item()

  print(f"Epoch: {epoch + 1}, Loss: {total_loss:.4f}")

Epoch: 1, Loss: 3.7247
Epoch: 2, Loss: 3.3890
Epoch: 3, Loss: 3.4274
Epoch: 4, Loss: 3.2855
Epoch: 5, Loss: 3.1942
Epoch: 6, Loss: 3.3133
Epoch: 7, Loss: 3.1679
Epoch: 8, Loss: 3.0715
Epoch: 9, Loss: 3.1751
Epoch: 10, Loss: 2.9764
Epoch: 11, Loss: 3.0471
Epoch: 12, Loss: 2.9485
Epoch: 13, Loss: 2.8292
Epoch: 14, Loss: 2.9082
Epoch: 15, Loss: 2.8319
Epoch: 16, Loss: 2.9126
Epoch: 17, Loss: 2.9639
Epoch: 18, Loss: 2.9229
Epoch: 19, Loss: 2.7152
Epoch: 20, Loss: 2.8259
Epoch: 21, Loss: 2.7415
Epoch: 22, Loss: 2.6474
Epoch: 23, Loss: 2.6528
Epoch: 24, Loss: 2.7625
Epoch: 25, Loss: 2.7477
Epoch: 26, Loss: 2.7603
Epoch: 27, Loss: 2.5430
Epoch: 28, Loss: 2.6176
Epoch: 29, Loss: 2.7957
Epoch: 30, Loss: 2.6948
Epoch: 31, Loss: 2.5546
Epoch: 32, Loss: 2.6958
Epoch: 33, Loss: 2.6517
Epoch: 34, Loss: 2.5594
Epoch: 35, Loss: 2.5870
Epoch: 36, Loss: 2.5774
Epoch: 37, Loss: 2.5934
Epoch: 38, Loss: 2.6397
Epoch: 39, Loss: 2.6127
Epoch: 40, Loss: 2.5494
Epoch: 41, Loss: 2.4845
Epoch: 42, Loss: 2.4199
E

Prediction

In [45]:
def prediction(model,vocab,text):

  #tokenize
  tokenized_text = word_tokenize(text.lower())

  # print(tokenized_text)


  #numerical indices
  numerical_text = text_to_indices(tokenized_text,vocab)

  # print(numerical_text)

  #padding
  padded_text = torch.tensor([0]* (25-len(numerical_text)) + numerical_text , dtype=torch.long).unsqueeze(0)

  # print(padded_text)

  # print(len(padded_text))

  # print(padded_text.shape)


  #send to model
  output = model(padded_text)

  # print("model's output",output)

  # print("printing total_elements",len(output[0]))

  #predicted index

  value, index = torch.max(output,dim=1)

  # print(f"printing value and index {value}, {index}")

  # print(f"printing  index  {index}")

  # print("printing the word ")

  # print(list(vocab.keys())[index])

  #merge with text

  return text + " " + list(vocab.keys())[index]





In [46]:
prediction(model,vocab,"Hi how are you the station was")

'Hi how are you the station was nearly'

In [47]:
import time
num_tokens = 20
input_text= 'Daniel checked the ticket'

for i in range(num_tokens):
  output_text = prediction(model,vocab,input_text)
  print(output_text)
  input_text = output_text
  time.sleep(0.5)


Daniel checked the ticket in
Daniel checked the ticket in his
Daniel checked the ticket in his pocket
Daniel checked the ticket in his pocket and
Daniel checked the ticket in his pocket and walked
Daniel checked the ticket in his pocket and walked toward
Daniel checked the ticket in his pocket and walked toward the
Daniel checked the ticket in his pocket and walked toward the train
Daniel checked the ticket in his pocket and walked toward the train .
Daniel checked the ticket in his pocket and walked toward the train . .
Daniel checked the ticket in his pocket and walked toward the train . . .
Daniel checked the ticket in his pocket and walked toward the train . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . .
Daniel checked the ticket in his pocket and walked toward the train . . . . . . . .

accuracy

In [48]:
def calculate_accuracy(model,dataloader,device):

  model.eval() #set the model to evaluation mode

  correct = 0
  total = 0

  with torch.no_grad():
    for batch_x, batch_y in dataloader:
      # print(len(batch_x)),len(batch_y)
      batch_x, batch_y = batch_x.to(device), batch_y.to(device)

      #get model prediction
      output = model(batch_x)

      # print(len(output[0]))

      #get the predictec word indices

      _, predicted = torch.max(output,dim=1)

      # print("printing predicted",predicted)

      #compare wityh actual label

      # print("printing y lable",batch_y)

      # print(predicted == batch_y)
      correct += (predicted == batch_y).sum().item()

      # print(correct)
      # print("working with total",batch_y.size())
      total += batch_y.size(0)

    accuracy = correct / total * 100
    return accuracy

In [49]:
accuracy = calculate_accuracy(model,dataloader,device)

print(f" Model accuracy {accuracy :.2f}%")

 Model accuracy 95.50%
