<a href="https://colab.research.google.com/github/Numan552/Deep-Learning/blob/main/RNN(simple_project).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/qna_dataset_605.csv")
df

,Question,Answer
0,Hi,Hello
1,Hello,Hi there
2,Good morning,Good morning
3,Good night,Good night
4,How are you,I am doing well
...,...,...
600,What is networking concept 146?,Networking concept 146 is related to computer ...
601,What is networking concept 147?,Networking concept 147 is related to computer ...
602,What is networking concept 148?,Networking concept 148 is related to computer ...
603,What is networking concept 149?,Networking concept 149 is related to computer ...


In [ ]:
df['Question']

,Question
0,Hi
1,Hello
2,Good morning
3,Good night
4,How are you
...,...
600,What is networking concept 146?
601,What is networking concept 147?
602,What is networking concept 148?
603,What is networking concept 149?


Tokenization

In [ ]:
import re

def tokenize(text):
    text = text.lower()                      # lowercase
    text = re.sub(r"[\"']", "", text)        # remove quotes
    text = re.sub(r"[^a-z0-9\s]", " ", text) # remove punctuation
    text = re.sub(r"\s+", " ", text).strip() # replace multiple spaces with one

    tokens = text.split()                    # tokenize into words
    return tokens

In [ ]:
print (tokenize(df['Question'][5]))

['what', 'is', 'python', 'topic', '1']


Vocab Forming

In [ ]:
vocab = {'<UNK>':0}

In [ ]:
def build_voceb (row):

  #print(row['Question'], row['Answer'])

  tokenized_question = tokenize(row['Question'])
  tokenized_answer = tokenize(row['Answer'])

  merged_tokens = tokenized_question + tokenized_answer

  # print (merged_tokens)

  for token in merged_tokens:
    if token not in vocab:
      vocab[token]=len(vocab)

In [ ]:
df.apply(build_voceb, axis =1)

,0
0,None
1,None
2,None
3,None
4,None
...,...
600,None
601,None
602,None
603,None


In [ ]:
vocab

{'<UNK>': 0,
 'hi': 1,
 'hello': 2,
 'there': 3,
 'good': 4,
 'morning': 5,
 'night': 6,
 'how': 7,
 'are': 8,
 'you': 9,
 'i': 10,
 'am': 11,
 'doing': 12,
 'well': 13,
 'what': 14,
 'is': 15,
 'python': 16,
 'topic': 17,
 '1': 18,
 'a': 19,
 'programming': 20,
 'concept': 21,
 '2': 22,
 '3': 23,
 '4': 24,
 '5': 25,
 '6': 26,
 '7': 27,
 '8': 28,
 '9': 29,
 '10': 30,
 '11': 31,
 '12': 32,
 '13': 33,
 '14': 34,
 '15': 35,
 '16': 36,
 '17': 37,
 '18': 38,
 '19': 39,
 '20': 40,
 '21': 41,
 '22': 42,
 '23': 43,
 '24': 44,
 '25': 45,
 '26': 46,
 '27': 47,
 '28': 48,
 '29': 49,
 '30': 50,
 '31': 51,
 '32': 52,
 '33': 53,
 '34': 54,
 '35': 55,
 '36': 56,
 '37': 57,
 '38': 58,
 '39': 59,
 '40': 60,
 '41': 61,
 '42': 62,
 '43': 63,
 '44': 64,
 '45': 65,
 '46': 66,
 '47': 67,
 '48': 68,
 '49': 69,
 '50': 70,
 '51': 71,
 '52': 72,
 '53': 73,
 '54': 74,
 '55': 75,
 '56': 76,
 '57': 77,
 '58': 78,
 '59': 79,
 '60': 80,
 '61': 81,
 '62': 82,
 '63': 83,
 '64': 84,
 '65': 85,
 '66': 86,
 '67': 87,
 '6

# Text to Indices

In [ ]:
def text_to_indices(text,vocab):
  indexed_text = []

  for token in tokenize(text):
    if token in vocab:
      # print(vocab[token])
      indexed_text.append(vocab[token])

    else:
      indexed_text.append(vocab['<UNK>'])

  return indexed_text


In [ ]:
text_to_indices("What is Phitron", vocab)

[14, 15, 0]

# Dataset and Data loader

In [ ]:
import torch
from torch.utils.data import Dataset,DataLoader

In [ ]:
df.shape[0]

605

In [ ]:
index =0
text_to_indices(df.iloc[index]['Question'],vocab)

[1]

In [ ]:
class QADataset(Dataset):

  def __init__(self , df,vocab):
    self.df =df
    self.vocab =vocab
  def __len__(self):
    return self.df.shape[0]
  def __getitem__(self,index):
    numerical_question = text_to_indices (self.df.iloc[index]['Question'],self.vocab)
    numerical_answer = text_to_indices (self.df.iloc[index]['Answer'],self.vocab)

    return torch.tensor(numerical_question), torch.tensor(numerical_answer)


In [ ]:
dataset = QADataset(df, vocab)

In [ ]:
dataset[1]

(tensor([2]), tensor([1, 3]))

In [ ]:
dataloader = DataLoader(dataset , batch_size=1 , shuffle=True)

In [ ]:
for Question, Answer in dataloader:
  print(Question, Answer[0])

tensor([[ 14,  15,  16,  17, 143]]) tensor([ 16,  17, 143,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21, 166]]) tensor([184,  21, 166,  15, 179, 180, 185, 186])
tensor([[14, 15, 16, 17, 65]]) tensor([16, 17, 65, 15, 19, 20, 21])
tensor([[ 14,  15, 178,  21, 147]]) tensor([178,  21, 147,  15, 179, 180, 177, 181, 182, 183])
tensor([[14, 15, 16, 17, 74]]) tensor([16, 17, 74, 15, 19, 20, 21])
tensor([[ 14,  15, 171, 172,  21,  29]]) tensor([171, 172,  21,  29, 173, 174, 175, 176, 177])
tensor([[ 14,  15, 178,  21, 141]]) tensor([178,  21, 141,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 178,  21,  18]]) tensor([178,  21,  18,  15, 179, 180, 177, 181, 182, 183])
tensor([[ 14,  15, 171, 172,  21, 109]]) tensor([171, 172,  21, 109, 173, 174, 175, 176, 177])
tensor([[ 14,  15,  16,  17, 168]]) tensor([ 16,  17, 168,  15,  19,  20,  21])
tensor([[ 14,  15, 184,  21,  78]]) tensor([184,  21,  78,  15, 179, 180, 185, 186])
tensor([[ 14,  15, 178,  21, 113]]) tensor([178,  21, 113, 

squeeze

In [ ]:
import torch

x=torch.tensor([[[1,2,3]]])

print(x.shape)

y= x.squeeze(0)
print(y.shape)

torch.Size([1, 1, 3])
torch.Size([1, 3])


# RNN architecture implementation

In [ ]:
import torch.nn as nn

class simpleRNN(nn.Module):
  def __init__(self, vocab_size , embedding_dim =50 , hidden_size=64):
    super().__init__()

    self.embedding = nn.Embedding(vocab_size , embedding_dim)
    self.rnn = nn.RNN(embedding_dim , hidden_size, batch_first=True)
    self.fc = nn.Linear(hidden_size, vocab_size)

  def forward (self, Question):
    embedded = self.embedding(Question)
    _,final = self.rnn(embedded)

    return self.fc(final.squeeze(0))

In [ ]:
model = simpleRNN(vocab_size=len(vocab))

# Training loop

In [ ]:
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)
epochs =50

In [ ]:
for epoch in range(epochs):
  total_loss=0
  for Question,Answer in dataloader:
    optimizer.zero_grad()
    output = model(Question)

    target = Answer[0][0].unsqueeze(0)

    loss = criterion(output, target)
    loss.backward()
    optimizer.step()
    total_loss+=loss.item()

  if (epoch + 1) % 10 == 0:
    print(f"Epoch{epoch+1:3d}/{epochs}|Loss:{total_loss:.4f}")

Epoch 10/50|Loss:21.0342
Epoch 20/50|Loss:2.9516
Epoch 30/50|Loss:0.3785
Epoch 40/50|Loss:0.0653
Epoch 50/50|Loss:0.0135


# Prediction

In [ ]:
vocab.items()

dict_items([('<UNK>', 0), ('hi', 1), ('hello', 2), ('there', 3), ('good', 4), ('morning', 5), ('night', 6), ('how', 7), ('are', 8), ('you', 9), ('i', 10), ('am', 11), ('doing', 12), ('well', 13), ('what', 14), ('is', 15), ('python', 16), ('topic', 17), ('1', 18), ('a', 19), ('programming', 20), ('concept', 21), ('2', 22), ('3', 23), ('4', 24), ('5', 25), ('6', 26), ('7', 27), ('8', 28), ('9', 29), ('10', 30), ('11', 31), ('12', 32), ('13', 33), ('14', 34), ('15', 35), ('16', 36), ('17', 37), ('18', 38), ('19', 39), ('20', 40), ('21', 41), ('22', 42), ('23', 43), ('24', 44), ('25', 45), ('26', 46), ('27', 47), ('28', 48), ('29', 49), ('30', 50), ('31', 51), ('32', 52), ('33', 53), ('34', 54), ('35', 55), ('36', 56), ('37', 57), ('38', 58), ('39', 59), ('40', 60), ('41', 61), ('42', 62), ('43', 63), ('44', 64), ('45', 65), ('46', 66), ('47', 67), ('48', 68), ('49', 69), ('50', 70), ('51', 71), ('52', 72), ('53', 73), ('54', 74), ('55', 75), ('56', 76), ('57', 77), ('58', 78), ('59', 79),

In [ ]:
idx_to_word = {idx:word for word, idx in vocab.items()}
idx_to_word

{0: '<UNK>',
 1: 'hi',
 2: 'hello',
 3: 'there',
 4: 'good',
 5: 'morning',
 6: 'night',
 7: 'how',
 8: 'are',
 9: 'you',
 10: 'i',
 11: 'am',
 12: 'doing',
 13: 'well',
 14: 'what',
 15: 'is',
 16: 'python',
 17: 'topic',
 18: '1',
 19: 'a',
 20: 'programming',
 21: 'concept',
 22: '2',
 23: '3',
 24: '4',
 25: '5',
 26: '6',
 27: '7',
 28: '8',
 29: '9',
 30: '10',
 31: '11',
 32: '12',
 33: '13',
 34: '14',
 35: '15',
 36: '16',
 37: '17',
 38: '18',
 39: '19',
 40: '20',
 41: '21',
 42: '22',
 43: '23',
 44: '24',
 45: '25',
 46: '26',
 47: '27',
 48: '28',
 49: '29',
 50: '30',
 51: '31',
 52: '32',
 53: '33',
 54: '34',
 55: '35',
 56: '36',
 57: '37',
 58: '38',
 59: '39',
 60: '40',
 61: '41',
 62: '42',
 63: '43',
 64: '44',
 65: '45',
 66: '46',
 67: '47',
 68: '48',
 69: '49',
 70: '50',
 71: '51',
 72: '52',
 73: '53',
 74: '54',
 75: '55',
 76: '56',
 77: '57',
 78: '58',
 79: '59',
 80: '60',
 81: '61',
 82: '62',
 83: '63',
 84: '64',
 85: '65',
 86: '66',
 87: '67',
 88

In [ ]:
def predict(question_text , model, vocab , idx_to_word):
  model.eval()

  with torch.no_grad():
    indices = text_to_indices( question_text , vocab)

    if not indices:
      return"<UNK>"

    x= torch.tensor(indices).unsqueeze(0)

    pred = torch.argmax(model(x),dim=1).item()

  return idx_to_word.get(pred,"<UNK>")

test

In [ ]:
tests =[
    "Hi",
    "Good morning",
    "How are you"

]

for q in tests:
  print(f"{q:45}={predict(q,model,vocab,idx_to_word)}")

Hi                                           =hello
Good morning                                 =good
How are you                                  =i
